baseURL = 'http://example.org/'
languageCode = 'es'
title = 'Imitaci√≥n de Cristo'
theme = "shibui"

[params]
  author = "Your Name"
  email = "your.email@example.com"

[markup]
  defaultMarkdownHandler = "goldmark"
  # By default, Goldmark trims unsafe outputs which might prevent some shortcodes from rendering.
  # It is recommended to set markup.goldmark.renderer.unsafe=true if you encounter problems.
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    tabWidth = 4
    style = "algol_nu"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[menu]
  [[menu.main]]
    name = ""
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = ""
    url = "/about/"
    weight = 2

